"""Generate Snapline icons (no external deps) — a rounded square with screenshot
crop-frame brackets. Writes build/icon.png (app/installer) and emits the tray icon
inline as a data URL in src/main/icons.generated.ts."""
import base64
import os
import struct
import zlib

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def lerp(a, b, t):
    return int(round(a + (b - a) * t))


def make_png(size):
    r = size * 0.235          # corner radius
    t = max(2, size * 0.055)  # bracket thickness
    length = size * 0.24      # bracket arm length
    inset = size * 0.22       # distance from edge

    # gradient endpoints (indigo -> violet)
    c0 = (99, 102, 241)
    c1 = (168, 85, 247)
    white = (248, 250, 252)

    def in_rounded(x, y):
        # rounded-rect coverage test
        cx = min(max(x, r), size - r)
        cy = min(max(y, r), size - r)
        dx = x - cx
        dy = y - cy
        return (dx * dx + dy * dy) <= (r * r)

    def in_brackets(x, y):
        near_l = x >= inset and x <= inset + length
        near_r = x <= size - inset and x >= size - inset - length
        near_t = y >= inset and y <= inset + length
        near_b = y <= size - inset and y >= size - inset - length
        vbar_l = inset <= x <= inset + t
        vbar_r = size - inset - t <= x <= size - inset
        hbar_t = inset <= y <= inset + t
        hbar_b = size - inset - t <= y <= size - inset
        # top-left
        if (vbar_l and near_t) or (hbar_t and near_l):
            return True
        # top-right
        if (vbar_r and near_t) or (hbar_t and near_r):
            return True
        # bottom-left
        if (vbar_l and near_b) or (hbar_b and near_l):
            return True
        # bottom-right
        if (vbar_r and near_b) or (hbar_b and near_r):
            return True
        return False

    raw = bytearray()
    for y in range(size):
        raw.append(0)  # filter type 0
        for x in range(size):
            if not in_rounded(x + 0.5, y + 0.5):
                raw.extend((0, 0, 0, 0))
                continue
            tcol = ((x / size) + (y / size)) / 2
            bg = (lerp(c0[0], c1[0], tcol), lerp(c0[1], c1[1], tcol), lerp(c0[2], c1[2], tcol))
            if in_brackets(x + 0.5, y + 0.5):
                raw.extend((white[0], white[1], white[2], 255))
            else:
                raw.extend((bg[0], bg[1], bg[2], 255))

    def chunk(tag, data):
        return (struct.pack(">I", len(data)) + tag + data +
                struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF))

    ihdr = struct.pack(">IIBBBBB", size, size, 8, 6, 0, 0, 0)
    png = b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", ihdr) + \
        chunk(b"IDAT", zlib.compress(bytes(raw), 9)) + chunk(b"IEND", b"")
    return png


def main():
    os.makedirs(os.path.join(ROOT, "build"), exist_ok=True)
    app_png = make_png(256)
    with open(os.path.join(ROOT, "build", "icon.png"), "wb") as f:
        f.write(app_png)

    tray_png = make_png(32)
    tray_b64 = base64.b64encode(tray_png).decode()
    app_b64 = base64.b64encode(app_png).decode()
    ts = (
        "// AUTO-GENERATED by scripts/generate_icons.py — do not edit by hand.\n"
        f"export const TRAY_ICON_DATA_URL = 'data:image/png;base64,{tray_b64}'\n"
        f"export const APP_ICON_DATA_URL = 'data:image/png;base64,{app_b64}'\n"
    )
    with open(os.path.join(ROOT, "src", "main", "icons.generated.ts"), "w", encoding="utf-8") as f:
        f.write(ts)
    print("Wrote build/icon.png and src/main/icons.generated.ts")


if __name__ == "__main__":
    main()
